version: "3"
services:
  app:
    container_name: springwork2000g0_app
    build:
      context: ../../
      dockerfile: ./docker/production/java/Dockerfile
    image: diamond.u-gakugei.ac.jp/springwork2000g0_app

  mysql:
    container_name: springwork2000g0_db
    build:
      context: ../../
      dockerfile: ./docker/production/mysql/Dockerfile
    image: diamond.u-gakugei.ac.jp/springwork2000g0_db
