version: "3"
services:
  app:
    container_name: onsen_app
    build:
      context: ../../
      dockerfile: ./docker/production/java/Dockerfile
    image: diamond.u-gakugei.ac.jp/onsen_app

  mysql:
    container_name: onsen_db
    build:
      context: ../../
      dockerfile: ./docker/production/mysql/Dockerfile
    image: diamond.u-gakugei.ac.jp/onsen_db
